version: '3.9'
services:
  # MySQL Database Service
  db:
    container_name: mps_mysql
    build:
      context: ${DOCKER_CONTEXT}
      dockerfile: development/mysql/Dockerfile
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: unless-stopped
    environment:
      TZ: 'Europe/Moscow'
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
    ports:
      # Maps port 33061 on the host to port 33061 on the MySQL container
      - "${MYSQL_PORT}:${MYSQL_PORT}"
    volumes:
      - mysql_data:/var/lib/mysql

  # PHP-FPM Service
  php-fpm:
    container_name: mps_php-fpm
    build:
      context: ${DOCKER_CONTEXT}
      dockerfile: development/php-fpm/Dockerfile
    restart: unless-stopped
#    tty: true
    volumes:
      # Mounts the local 'app' directory to the container's Nginx root
      - "${APP_VOLUMES_HOST}:${APP_VOLUMES_CONTAINER}"
#    depends_on:
#      - db
#    ports:
#      - "9000:9000"
    environment:
      APP_ENV: dev
      APP_DEBUG: 1
      PHP_IDE_CONFIG: serverName=ELA
      DB_HOST: mysql
      DB_USER: "${MYSQL_USER}"
      DB_PASSWORD: "${MYSQL_PASSWORD}"
      DB_NAME: "${MYSQL_DATABASE}"
      DATABASE_URL: "mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@db/${MYSQL_DATABASE}"

    # PHP-CLI Service
  php-cli:
    container_name: mps_php-cli
    build:
      context: ${DOCKER_CONTEXT}
      dockerfile: development/php-cli/Dockerfile
    restart: unless-stopped
    tty: true
    volumes:
      # Mounts the local 'app' directory to the container's Nginx root
      - "${APP_VOLUMES_HOST}:${APP_VOLUMES_CONTAINER}"
#    depends_on:
#      - db
#    ports:
#      - "9000:9000"
    environment:
      APP_ENV: dev
      APP_DEBUG: 1
      PHP_IDE_CONFIG: serverName=MPS
      DB_HOST: mysql
      DB_USER: "${MYSQL_USER}"
      DB_PASSWORD: "${MYSQL_PASSWORD}"
      DB_NAME: "${MYSQL_DATABASE}"
      DATABASE_URL: "mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@db/${MYSQL_DATABASE}"

  # NGINX Service
  nginx:
    container_name: mps_nginx
    build:
      context: ${DOCKER_CONTEXT}
      dockerfile: development/nginx/Dockerfile
    volumes:
      # Mount local 'app' directory to the Nginx root
      - "${APP_VOLUMES_HOST}:${APP_VOLUMES_CONTAINER}"
    restart: unless-stopped
    depends_on:
      - db
      - php-fpm
    ports:
      - "${NGINX_PORT_HOST}:${NGINX_PORT_CONTAINER}"

  adminer:
    image: adminer
    restart: always
    ports:
      - "8808:8080"

volumes:
  mysql_data:
