# app/config/routes.yaml

################ Home ##################
home:
    resource:
        path: ../src/Module/Home/UI/Http/Web/Controller/
        namespace: App\Module\Home\UI\Http\Web\Controller
    type: attribute


################ Auth ##################
app_login:
    resource:
        path: ../src/Module/Auth/UI/Http/Web/Controller/Login
        namespace: App\Module\Auth\UI\Http\Web\Controller\Login
    type: attribute

app_logout:
    resource:
        path: ../src/Module/Auth/UI/Http/Web/Controller/Logout
        namespace: App\Module\Auth\UI\Http\Web\Controller\Logout
    type: attribute

################ Auth ##################
#auth_reset:
#    resource:
#        path: ../src/Module/Auth/UI/Http/Web/Controller/Reset
#        namespace: App\Module\Auth\UI\Http\Web\Controller\Reset
#    type: attribute

auth_signup:
    resource:
        path: ../src/Module/Auth/UI/Http/Web/Controller/SignUp
        namespace: App\Module\Auth\UI\Http\Web\Controller\SignUp
    type: attribute


################ Admin ##################
admin_dashboard:
    resource:
        path: ../src/Module/Admin/Dashboard/UI/Http/Web/Controller
        namespace: App\Module\Admin\Dashboard\UI\Http\Web\Controller
    type: attribute
admin_auth:
    resource:
        path: ../src/Module/Admin/Auth/UI/Http/Web/Controller
        namespace: App\Module\Admin\Auth\UI\Http\Web\Controller
    type: attribute


################ Order ##################
order_create:
    resource:
        path: ../src/Module/Shop/Order/Order/UI/Http/Web/Controller/Create/
        namespace: App\Module\Shop\Order\Order\UI\Http\Web\Controller\Create
    type: attribute
