app_home:
    path: /
    controller: App\Home\UI\Http\Web\Controller\Home\Controller
    methods: [GET]

#app_login:
#    path: /login
#    controller: App\Ui\Http\Controller\Auth\Login\Controller
#    methods: [GET]
#
#app_order:
#    path: /order
#    controller: App\Ui\Http\Controller\Shop\Order\Order\Controller
#    methods: [GET]
#
#app_ordering:
#    path: /ordering
#    controller: App\Ui\Http\Controller\Shop\Order\Ordering\Controller
#    methods: [GET, POST]
