# config/routes/attributes.yaml
controllers:
    resource:
        path: ../../src/Module/Home/UI/Http/Web/Controller/
        namespace: App\Module\Home\UI\Http\Web\Controller
    type: attribute

kernel:
    resource: App\Kernel
    type: attribute