doctrine_migrations:
    migrations_paths:
        App\Migrations: '%kernel.project_dir%/src/Infrastructure/Doctrine/Migrations'
        Auth\Migrations: '%kernel.project_dir%/src/Domain/Auth/Infrastructure/Doctrine/Migrations'
        Shop\Migrations: '%kernel.project_dir%/src/Domain/Shop/Infrastructure/Doctrine/Migrations'
        # namespace is arbitrary but should be different from App\Migrations
        # as migrations classes should NOT be autoloaded
    enable_profiler: false
