doctrine:
    dbal:
        driver: pdo_mysql
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        server_version: '8.3.0'

        profiling_collect_backtrace: '%kernel.debug%'
        use_savepoints: true

        types:
#            user_id:  App\Domain\Model\Auth\Entity\User\Entity\UserIdType
#            user_email:  App\Domain\Model\Auth\Entity\User\Entity\UserEmailType
#            user_role:  App\Domain\Model\Auth\Entity\User\Entity\UserRoleType
#            user_password: App\Domain\Model\Auth\Entity\User\Entity\UserPasswordType

#            money_amount_type: App\Infrastructure\Doctrine\Dbal\Type\Money\MoneyAmountType
#            money_currency_type: App\Infrastructure\Doctrine\Dbal\Type\Money\MoneyCurrencyType

#            category_id: App\Domain\Model\Shop\Entity\Category\Entity\CategoryIdType
#            category_name: App\Domain\Model\Shop\Entity\Category\Entity\CategoryNameType
#
#            good_id:  App\Domain\Model\Shop\Entity\Category\Entity\Good\Entity\GoodIdType
#            good_name:  App\Domain\Model\Shop\Entity\Category\Entity\Good\Entity\GoodNameType
#
#            order_id:  App\Domain\Model\Shop\Entity\Order\Entity\OrderIdType
#            order_cost:  App\Domain\Model\Shop\Entity\Order\Entity\OrderCostType
#            order_created:  App\Domain\Model\Shop\Entity\Order\Entity\OrderCreatedType

        mapping_types:
            enum: string

    orm:
        auto_generate_proxy_classes: true
        enable_lazy_ghost_objects: true
        report_fields_where_declared: true
        validate_xml_mapping: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
#            User:
#                type: attribute
#                is_bundle: false
#                dir: '%kernel.project_dir%/src/Domain/Model/Auth/Entity/User/Entity'
#                prefix: 'App\Domain\Model\Auth\Entity\User\Entity'
#                alias: User
#            Category:
#                type: attribute
#                is_bundle: false
#                dir: '%kernel.project_dir%/src/Domain/Model/Shop/Entity/Category/Entity'
#                prefix: 'App\Domain\Model\Shop\Entity\Category\Entity'
#                alias: Category
#            Good:
#                type: attribute
#                is_bundle: false
#                dir: '%kernel.project_dir%/src/Domain/Model/Shop/Entity/Category/Entity/Good/Entity'
#                prefix: 'App\Domain\Model\Shop\Entity\Category\Entity\Good\Entity'
#                alias: Good
#            Order:
#                type: attribute
#                is_bundle: false
#                dir: '%kernel.project_dir%/src/Domain/Model/Shop/Entity/Order/Entity'
#                prefix: 'App\Domain\Model\Shop\Entity\Order\Entity'
#                alias: Order

        controller_resolver:
            auto_mapping: true

when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
