doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        driver: 'pdo_pgsql'
        server_version: '16'
        charset: utf8
        profiling_collect_backtrace: '%kernel.debug%'
        use_savepoints: true

        types:

            user_id: App\Module\Auth\Infrastructure\Doctrine\Dbal\Type\UserIdType
            user_email: App\Module\Auth\Infrastructure\Doctrine\Dbal\Type\UserEmailType
            user_password: App\Module\Auth\Infrastructure\Doctrine\Dbal\Type\UserPasswordType
            user_status: App\Module\Auth\Infrastructure\Doctrine\Dbal\Type\UserStatus

            admin_id: App\Module\Admin\Auth\Infrastructure\Doctrine\Dbal\Type\Email\AdminIdType
            admin_username: App\Module\Admin\Auth\Infrastructure\Doctrine\Dbal\Type\Email\AdminUsernameType
            admin_email: App\Module\Admin\Auth\Infrastructure\Doctrine\Dbal\Type\Email\AdminEmailType
            admin_password: App\Module\Admin\Auth\Infrastructure\Doctrine\Dbal\Type\Email\AdminPasswordType
            admin_status: App\Module\Admin\Auth\Infrastructure\Doctrine\Dbal\Type\Email\AdminStatusType

    orm:
        auto_generate_proxy_classes: true
        enable_lazy_ghost_objects: true
        report_fields_where_declared: true
        validate_xml_mapping: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
#            App:
#                is_bundle: false
#                type: attribute
#                dir: '%kernel.project_dir%/src/Entity'
#                prefix: 'App\Entity'
#                alias: App

when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
