#config/packages/easy_admin.yaml

easy_admin:
#    resource: 'EasyAdmin'
#    prefix: /admin
#    type: attribute
    entities:
        # List the entity class name you want to manage
#        - App\Entity\Product
#        - App\Entity\Category
#        - App\Module\Auth\Domain\DomainModel\Entity\User\User