twig:
    file_name_pattern: '*.twig'
    form_themes: ['bootstrap_4_layout.html.twig']

    paths:
        "%kernel.project_dir%/src/Core/UI/Http/Web/Template" : core

        "%kernel.project_dir%/src/Module/Home/UI/Http/Web/Template" : home

        "%kernel.project_dir%/src/Module/Auth/UI/Http/Web/Template" : auth

        "%kernel.project_dir%/src/Module/Shop/Order/Order/UI/Http/Web/Template": order

when@test:
    twig:
        strict_variables: true
